---
- name: ejabberd required packages should be installed
  apt: pkg={{ item }} state=present
  with_items:
   - wget
   - libexpat1
   - erlang-nox
   - libyaml-0-2
   - python-jinja2
  tags: 
   - ejabberd
   
- name: download ejabberd
  get_url: url=http://www.process-one.net/downloads/ejabberd/14.12/ejabberd-14.12-linux-x86_64-installer.run 
    dest=/tmp/ejabberd-installer.run  mode=755
  #get_url: url=https://www.process-one.net/downloads/ejabberd/2.1.13/ejabberd-2.1.13-linux-x86-installer.run 
  #  dest=/tmp/ejabberd-installer.run  mode=755
  tags: 
   - ejabberd
   
#- name: create ejabberd home   
   
- name: create group ejabberd
  group: name=ejabberd state=present
  sudo: yes
  tags: ejabberd  
  
- name: create user ejabberd
  user: name=ejabberd state=present group=ejabberd home=/opt/ejabberd
  sudo: yes
  tags: ejabberd

- name: install ejabberd
  shell: /tmp/ejabberd-installer.run --mode unattended --prefix /opt/ejabberd --adminpw ejabberd
  sudo: yes
  tags:
   - ejabberd    

- name: configure ejabberd
  template: src=ejabberd.yml.tpl dest=/opt/ejabberd/conf/ejabberd.yml owner=ejabberd group=ejabberd mode=0600
  sudo: yes
  tags: ejabberd 
  
- name: configure ejabberdctl
  template: src=ejabberdctl.cfg.tpl dest=/opt/ejabberd/conf/ejabberdctl.cfg owner=ejabberd group=ejabberd mode=0600
  sudo: yes
  tags: ejabberd 

#- name: fix 
  
- name: start ejabberd
  shell: /opt/ejabberd/bin/ejabberdctl start
  sudo: yes
  tags: 
   - ejabberd
   
- name: waiting for ejabberd server to come back
  local_action: wait_for host={{ inventory_hostname }}
            state=started port=5222 delay=10 timeout=30
  sudo: false
   
- name: register ejabberd domain admin
  shell: /opt/ejabberd/bin/ejabberdctl register admin {{lider_ejabberd_domain}} admin
  sudo: yes
  tags: 
   - ejabberd
   - ejabberd-user
   


#- name: create shared roster group called everyone
#  shell: "/opt/ejabberd/bin/ejabberdctl srg-create everyone {{ lider_ejabberd_domain }} 'everyone' this_is_everyone everyone"
#  sudo: yes
#  tags:
#   - ejabberd
#   - ejabberdctl 

#- name: add all users to shared roster group called everyone
#  shell: "/opt/ejabberd/bin/ejabberdctl srg-user-add @all@  {{ lider_ejabberd_domain }} 'everyone' {{ lider_ejabberd_domain }}"
#  sudo: yes
#  tags:
#   - ejabberd
#   - ejabberdctl 


